### ISSUE TITLE
How to reset pomodoros

### ISSUE THREAD

**Issue by gEndelf** [dkandalov/pomodoro-tm#10]
The question is - how to reset pomodoro counter in new UI
version: 0.45

**Comment by dkandalov** [comment]
Not sure what you mean by new UI.
To reset pomodoro counter in toolwindow you can double click on "Pomodoro: ..." label.

(I do not think this is ok from UX point of view. It should really be redesigned.)

**Comment by gEndelf** [comment]
![untitled](https://cloud.githubusercontent.com/assets/310866/14452062/847110be-0094-11e6-8152-d5bc8aa62f4c.png)

@dkandalov Excuse me, but where could I click?
After last update I can click only on timer (window with counter not opened)

IDEA Ultimate, v. 2016.1.1, build IU-145.597

**Comment by dkandalov** [comment]
Resetting pomodoro counter only works from the "window with counter". There is "Pomodoro:" label.
To make pomodoro toolwindow visible you can enable it in IDE Settings -> Pomodoro.

Admittedly this is really bad UX :( 
Hopefully I will make it a bit better in the next couple weeks.

**Comment by gEndelf** [comment]
@dkandalov 
I I've found settings here:
**Settings -> Other settings -> Pomodoro** and checkbox **Show tool window**

Thx! Issue resolved
