### ISSUE TITLE
Custom work/break length

### ISSUE THREAD

**Issue by ervinsuhanko** [dkandalov/pomodoro-tm#11]
Maybe you can add some custom length for the work and break time.

**Comment by dkandalov** [comment]
It should be already available in ``IDE settings -> Other Settings -> Pomodoro``.

**Comment by ervinsuhanko** [comment]
Thanks for the quick reply. 
Right now you can select from giving values. I meant to add my custom time, like 150, 3 or maybe 60 minutes

**Comment by dkandalov** [comment]
Hm.. You should be able to type any value in the drop-down. 
Pre-defined values are just examples of what I though would be the most common durations.

**Comment by ervinsuhanko** [comment]
Oh yes, it's working, I can type in it,
Thanks!
