### ISSUE TITLE
How do I reset pomodoros to 0

### ISSUE THREAD

**Issue by eileenmcnaughton** [dkandalov/pomodoro-tm#20]
It seems to just keep incrementing them - it looks like double clicking the clock would do it from the code but it doesn't seem to.

I've found editing pomodoro.state.xml works but that feels like an overkill approach. (I also think that the longer break after 4 doesn't happen after 8, 12, 16 but still confirming that)

**Comment by dkandalov** [comment]
In plugin version 0.70 you should be able to find "Reset Pomodoro Counter" action or alt+click on the widget and choose this action.

**Comment by eileenmcnaughton** [comment]
Yes! thank you
