### ISSUE TITLE
IDE locked up completely even after break time finished

### ISSUE THREAD

**Issue by bcowgill** [dkandalov/pomodoro-tm#3]
I've installed this into WebStorm on Linux Ubuntu and the editor remains locked forever after the break time. The timer appears to be stuck at 00:01 so the editor stays locked.

**Comment by dkandalov** [comment]
Thanks a lot for reporting this.

Do you mind sharing a stacktrace?
It should be in idea.log file (the directory can be located in Main Menu -> Help -> Show Log)
or if the whole IDE was blocked, in one of the "threadDumps-..." folders.

I also suspect this might be related to playing ring sound on Linux (e.g. if you use IcedTea jdk).
To check this you can set ring volume to zero in IDE Settings -> Other settings -> Pomodoro.

**Comment by dkandalov** [comment]
This might be related to this issue with sound on Linux 
https://github.com/dkandalov/friday-mario/issues/3#issuecomment-160421286
